# Generated by Django 5.0.2 on 2024-03-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_include', models.BooleanField(default=False, verbose_name='Вложен ли пункт меню')),
                ('lvl_include', models.CharField(default=0, unique=True, verbose_name='Путь вложенности')),
                ('lvl_in_tree', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень вложенности')),
                ('path_the_root', models.CharField(default=0, verbose_name='Путь к началу наследования меню')),
                ('is_item_head', models.BooleanField(default=False, verbose_name='Является ли пункт меню заголовком')),
                ('prev_item_lvl_in_tree', models.PositiveIntegerField(verbose_name='Предыдущий элемент меню по уровню вложеннсоти')),
                ('item', models.CharField(max_length=255, verbose_name='Пункт меню')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_link', to='menu.item', verbose_name='привязка к верхнему уровню меню')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_menu', to='menu.menu', verbose_name='пункты меню относящиеся к этому меню')),
            ],
            options={
                'verbose_name': 'Настройка пункта меню',
                'verbose_name_plural': 'Настройка пунктов меню',
                'ordering': ['lvl_include'],
            },
        ),
    ]
